### ISSUE TITLE
Unable to strat the project according with README.MD

### ISSUE THREAD

**Issue by vmasilva** [googleapis/nodejs-security-center#293]
#### Problem Description:
Following the instructions provided by README.MD, I am not able to run locally the project. 
I get an error: (node:9817) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Invalid parent. 

#### Runtime:
- OS: Debian GNU/Linux 10 (buster)
- Node.js version: v14.5.0
- npm version: 6.14.5
- `@google-cloud/security-center` version: 5.0.0

#### Steps to reproduce

  1. git clone https://github.com/googleapis/nodejs-security-center.git
  2. cd nodejs-security-center/samples
  3. npm install
  4. export GOOGLE_APPLICATION_CREDENTIALS=/home/user/Downloads/gcp-000005-016325-13693d4130d4.json
(This service account has the following permissions at ORG Level: SC Asset Viewer, SC Findings Viewer, Organization Viewer )
  5. Enable Security Command Center API, in the same project as Service account belongs
  6. Run command node quickstart.js 
I get an error, so I run the command with flag --unhandled-rejections=strict
  7. node --unhandled-rejections=strict  quickstart.js
And I get another error. Then, I also change the Org ID in file quickstart.js 
    // TODO(developer): choose the organization to use
    const organization = '4867(...)';
   8. And repeated the steps 6 and 7, but i get the same errors. 
   9. I tried also passing the ORG ID by parameter in quickstart.js, but also have error. 

Please find the complete output in attachment.
[errors.txt](https://github.com/googleapis/nodejs-security-center/files/4859558/errors.txt)

Can anyone check please?

Thanks,
VS

**Comment by bcoe** [comment]
@vmasilva rather than your organization number, it should be the organization ID, e.g., `my-corp`. You should see this listed in the GCP UI, when you click the account drop down.

**Comment by vmasilva** [comment]
Hi @bcoe .
Thank you for help. 

I have modified from ORG ID to ORG descriptions (as I seen in dropdown list), but now I am getting another error:

node quickstart.js
(node:8365) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Invalid parent.
    at Object.callErrorFromStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:314:20)
    at emit (internal/http2/core.js:291:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----------------------------------------------------------------------------
----------------------------------------------------------------------------
(trying with --unhandled-rejections )

 node --unhandled-rejections=strict quickstart.js

/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call.js:30
    return Object.assign(new Error(message), status);
                         ^

Error: 3 INVALID_ARGUMENT: Invalid parent.
    at Object.callErrorFromStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/home/user/wip/gcp-secutiy-command-center/nodejs-security-center/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:314:20)
    at emit (internal/http2/core.js:291:8) {
  code: 3,
  details: 'Invalid parent.',
  metadata: Metadata {
    internalRepr: Map(1) {
      'grpc-server-stats-bin' => [
        Buffer(10) [Uint8Array] [
          0, 0, 24, 95, 147,
          1, 0,  0,  0,   0
        ]
      ]
    },
    options: {}
  }
}
user@debianvm:~/wip/gcp-secutiy-command-center/nodejs-security-center/samples$ 


Any idea?

Thanks.

**Comment by bcoe** [comment]
@vmasilva here's an example of `quickstart.js` being executed:

https://github.com/googleapis/nodejs-security-center/blob/master/samples/system-test/quickstart.test.js#L28

You shouldn't use the description of the organization, you want the string ID:

<img width="620" alt="Screen Shot 2020-07-08 at 2 26 50 PM" src="https://user-images.githubusercontent.com/194609/86972051-1ea16380-c127-11ea-893e-6274e8adfe73.png">

In my example above, this would be `oss-automation`. You should also ensure you're logged in locally:

1. install the [gcloud sdk](https://cloud.google.com/sdk/install).
2. run `gcloud auth login`.

**Comment by JustinBeckwith** [comment]
Greetings!  This bug has sit around for a bit, and looks like it was answered.  If you're running into issues still, please do let us know!
